version: 0.0
os: linux
files:
  - source: /app.py
  - source: /calculator/operations.py
  - source: /Dockerfile
  - source: /requirements.txt
  - source: /scripts/stop_container.sh
  - source: /scripts/start_container.sh

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
